services:
  power-optimizer:
    container_name: service-power-optimizer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    #    expose:
    #      - 8501
    volumes:
      - ./:/deploy
    command:
      [
        'nohup',
        'streamlit',
        'run',
        'server.py',
        '--server.port',
        '8501',
        '--server.baseUrlPath',
        '/power-optimizer',
        '--theme.base',
        'dark',
        '&',
        '--server.runOnSave',
        'true',
      ]
    networks:
      - service-network

networks:
  service-network:
    name: service-network
    driver: bridge
    external: true
